In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('weather.csv')
df

Data.Precipitation   Date.Full  Date.Month  Date.Week of  Date.Year  \
0                    0.00  2016-01-03           1             3       2016   
1                    0.00  2016-01-03           1             3       2016   
2                    0.16  2016-01-03           1             3       2016   
3                    0.00  2016-01-03           1             3       2016   
4                    0.01  2016-01-03           1             3       2016   
...                   ...         ...         ...           ...        ...   
16738                0.08  2017-01-01           1             1       2017   
16739                0.00  2017-01-01           1             1       2017   
16740                0.00  2017-01-01           1             1       2017   
16741                0.06  2017-01-01           1             1       2017   
16742                0.10  2017-01-01           1             1       2017   

      Station.City Station.Code Station.Location Station.State  \
0       Birmingham          BHM   Birmingham, AL       Alabama   
1       Huntsville          HSV   Huntsville, AL       Alabama   
2           Mobile          MOB       Mobile, AL       Alabama   
3       Montgomery          MGM   Montgomery, AL       Alabama   
4        Anchorage          ANC    Anchorage, AK        Alaska   
...            ...          ...              ...           ...   
16738       Casper          CPR       Casper, WY       Wyoming   
16739     Cheyenne          CYS     Cheyenne, WY       Wyoming   
16740       Lander          LND       Lander, WY       Wyoming   
16741      Rawlins          RWL      Rawlins, WY       Wyoming   
16742     Sheridan          SHR     Sheridan, WY       Wyoming   

       Data.Temperature.Avg Temp  Data.Temperature.Max Temp  \
0                             39                         46   
1                             39                         47   
2                             46                         51   
3                             45                         52   
4                             34                         38   
...                          ...                        ...   
16738                         23                         32   
16739                         32                         42   
16740                         17                         29   
16741                         23                         31   
16742                         21                         34   

       Data.Temperature.Min Temp  Data.Wind.Direction  Data.Wind.Speed  
0                             32                   33             4.33  
1                             31                   32             3.86  
2                             41                   35             9.73  
3                             38                   32             6.86  
4                             29                   19             7.80  
...                          ...                  ...              ...  
16738                         15                   23            19.98  
16739                         21                   26            15.16  
16740                          4                   26             1.65  
16741                         13                   24            18.16  
16742                          8                   23             7.51  

[16743 rows x 14 columns]

# Get column/row

In [3]:
df.columns

Index(['Data.Precipitation', 'Date.Full', 'Date.Month', 'Date.Week of',
       'Date.Year', 'Station.City', 'Station.Code', 'Station.Location',
       'Station.State', 'Data.Temperature.Avg Temp',
       'Data.Temperature.Max Temp', 'Data.Temperature.Min Temp',
       'Data.Wind.Direction', 'Data.Wind.Speed'],
      dtype='object')

In [5]:
df[['Date.Year','Date.Full']]

Date.Year   Date.Full
0           2016  2016-01-03
1           2016  2016-01-03
2           2016  2016-01-03
3           2016  2016-01-03
4           2016  2016-01-03
...          ...         ...
16738       2017  2017-01-01
16739       2017  2017-01-01
16740       2017  2017-01-01
16741       2017  2017-01-01
16742       2017  2017-01-01

[16743 rows x 2 columns]

In [7]:
df[['Date.Year','Date.Full']][0:10].values

array([[2016, '2016-01-03'],
       [2016, '2016-01-03'],
       [2016, '2016-01-03'],
       [2016, '2016-01-03'],
       [2016, '2016-01-03'],
       [2016, '2016-01-03'],
       [2016, '2016-01-03'],
       [2016, '2016-01-03'],
       [2016, '2016-01-03'],
       [2016, '2016-01-03']], dtype=object)

In [8]:
df[['Date.Year','Date.Full']][0:10].index

RangeIndex(start=0, stop=10, step=1)

In [12]:
list(df[['Date.Year','Date.Full']][0:10].values)[2:]

[array([2016, '2016-01-03'], dtype=object),
 array([2016, '2016-01-03'], dtype=object),
 array([2016, '2016-01-03'], dtype=object),
 array([2016, '2016-01-03'], dtype=object),
 array([2016, '2016-01-03'], dtype=object),
 array([2016, '2016-01-03'], dtype=object),
 array([2016, '2016-01-03'], dtype=object),
 array([2016, '2016-01-03'], dtype=object)]

# loc

In [15]:
df.loc[20:30][['Date.Full','Date.Year']]

Date.Full  Date.Year
20  2016-01-03       2016
21  2016-01-03       2016
22  2016-01-03       2016
23  2016-01-03       2016
24  2016-01-03       2016
25  2016-01-03       2016
26  2016-01-03       2016
27  2016-01-03       2016
28  2016-01-03       2016
29  2016-01-03       2016
30  2016-01-03       2016

In [16]:
df.loc[20:30][['Date.Full','Date.Year']].values

array([['2016-01-03', 2016],
       ['2016-01-03', 2016],
       ['2016-01-03', 2016],
       ['2016-01-03', 2016],
       ['2016-01-03', 2016],
       ['2016-01-03', 2016],
       ['2016-01-03', 2016],
       ['2016-01-03', 2016],
       ['2016-01-03', 2016],
       ['2016-01-03', 2016],
       ['2016-01-03', 2016]], dtype=object)

In [17]:
df.loc[20:30][['Date.Full','Date.Year']].index

RangeIndex(start=20, stop=31, step=1)

In [21]:
list(df.loc[20:30][['Date.Full','Date.Year']].values)[-1]

array(['2016-01-03', 2016], dtype=object)

# Condition

In [23]:
df['Date.Year']==2016

0         True
1         True
2         True
3         True
4         True
         ...  
16738    False
16739    False
16740    False
16741    False
16742    False
Name: Date.Year, Length: 16743, dtype: bool

In [25]:
df.loc[(df['Date.Year']==2016)&(df['Date.Month']>6)]

Data.Precipitation   Date.Full  Date.Month  Date.Week of  Date.Year  \
8209                 0.00  2016-07-03           7             3       2016   
8210                 0.06  2016-07-03           7             3       2016   
8211                 0.00  2016-07-03           7             3       2016   
8212                 0.00  2016-07-03           7             3       2016   
8213                 0.35  2016-07-03           7             3       2016   
...                   ...         ...         ...           ...        ...   
16421                0.39  2016-12-25          12            25       2016   
16422                0.04  2016-12-25          12            25       2016   
16423                0.33  2016-12-25          12            25       2016   
16424                0.36  2016-12-25          12            25       2016   
16425                0.30  2016-12-25          12            25       2016   

      Station.City Station.Code Station.Location Station.State  \
8209    Birmingham          BHM   Birmingham, AL       Alabama   
8210    Huntsville          HSV   Huntsville, AL       Alabama   
8211        Mobile          MOB       Mobile, AL       Alabama   
8212    Montgomery          MGM   Montgomery, AL       Alabama   
8213     Anchorage          ANC    Anchorage, AK        Alaska   
...            ...          ...              ...           ...   
16421       Casper          CPR       Casper, WY       Wyoming   
16422     Cheyenne          CYS     Cheyenne, WY       Wyoming   
16423       Lander          LND       Lander, WY       Wyoming   
16424      Rawlins          RWL      Rawlins, WY       Wyoming   
16425     Sheridan          SHR     Sheridan, WY       Wyoming   

       Data.Temperature.Avg Temp  Data.Temperature.Max Temp  \
8209                          84                         97   
8210                          82                         95   
8211                          84                         94   
8212                          86                         99   
8213                          59                         63   
...                          ...                        ...   
16421                         27                         37   
16422                         34                         45   
16423                         19                         32   
16424                         27                         37   
16425                         18                         34   

       Data.Temperature.Min Temp  Data.Wind.Direction  Data.Wind.Speed  
8209                          70                   27             3.50  
8210                          68                   28             3.00  
8211                          74                   24             3.86  
8212                          72                   23             2.76  
8213                          55                   23             2.80  
...                          ...                  ...              ...  
16421                         16                   24            15.61  
16422                         23                   24            10.85  
16423                          6                   23             2.31  
16424                         17                   23            13.72  
16425                          3                   23             5.64  

[8217 rows x 14 columns]

In [27]:
df.loc[(df['Date.Year']==2016)&(df['Date.Month']>6)][['Station.City','Station.Code']]

Station.City Station.Code
8209    Birmingham          BHM
8210    Huntsville          HSV
8211        Mobile          MOB
8212    Montgomery          MGM
8213     Anchorage          ANC
...            ...          ...
16421       Casper          CPR
16422     Cheyenne          CYS
16423       Lander          LND
16424      Rawlins          RWL
16425     Sheridan          SHR

[8217 rows x 2 columns]

In [28]:
df.loc[(df['Date.Year']==2016)&(df['Date.Month']>6)][['Station.City','Station.Code']].values

array([['Birmingham', 'BHM'],
       ['Huntsville', 'HSV'],
       ['Mobile', 'MOB'],
       ...,
       ['Lander', 'LND'],
       ['Rawlins', 'RWL'],
       ['Sheridan', 'SHR']], dtype=object)

In [29]:
df.loc[(df['Date.Year']==2016)&(df['Date.Month']>6)][['Station.City','Station.Code']].index

Int64Index([ 8209,  8210,  8211,  8212,  8213,  8214,  8215,  8216,  8217,
             8218,
            ...
            16416, 16417, 16418, 16419, 16420, 16421, 16422, 16423, 16424,
            16425],
           dtype='int64', length=8217)

In [32]:
list(df.loc[(df['Date.Year']==2016)&(df['Date.Month']>6)][['Station.City','Station.Code']].values)[5:]

[array(['Annette', 'ANN'], dtype=object),
 array(['Bethel', 'BET'], dtype=object),
 array(['Bettles', 'BTT'], dtype=object),
 array(['Cold Bay', 'CDB'], dtype=object),
 array(['Cordova', 'CDV'], dtype=object),
 array(['Delta Junction/Ft Greely', 'BIG'], dtype=object),
 array(['Fairbanks', 'FAI'], dtype=object),
 array(['Gulkana', 'GKN'], dtype=object),
 array(['Gustavus', 'GST'], dtype=object),
 array(['Homer', 'HOM'], dtype=object),
 array(['Iliamna', 'ILI'], dtype=object),
 array(['Juneau', 'JNU'], dtype=object),
 array(['Kenai', 'ENA'], dtype=object),
 array(['Ketchikan', 'KTN'], dtype=object),
 array(['King Salmon', 'AKN'], dtype=object),
 array(['Kodiak', 'ADQ'], dtype=object),
 array(['Kotzebue', 'OTZ'], dtype=object),
 array(['Mc Grath', 'MCG'], dtype=object),
 array(['Nome', 'OME'], dtype=object),
 array(['Northway', 'ORT'], dtype=object),
 array(['Palmer', 'PAQ'], dtype=object),
 array(['Petersburg', 'PSG'], dtype=object),
 array(['Puntilla Lake', 'PTI'], dtype=object),
 array

# iloc

In [37]:
df.iloc[20:30,0:5]

Data.Precipitation   Date.Full  Date.Month  Date.Week of  Date.Year
20                0.10  2016-01-03           1             3       2016
21                0.01  2016-01-03           1             3       2016
22                0.08  2016-01-03           1             3       2016
23                0.00  2016-01-03           1             3       2016
24                0.40  2016-01-03           1             3       2016
25                0.00  2016-01-03           1             3       2016
26                0.00  2016-01-03           1             3       2016
27                0.00  2016-01-03           1             3       2016
28                0.37  2016-01-03           1             3       2016
29                0.55  2016-01-03           1             3       2016

In [34]:
df.loc[20:30]

Data.Precipitation   Date.Full  Date.Month  Date.Week of  Date.Year  \
20                0.10  2016-01-03           1             3       2016   
21                0.01  2016-01-03           1             3       2016   
22                0.08  2016-01-03           1             3       2016   
23                0.00  2016-01-03           1             3       2016   
24                0.40  2016-01-03           1             3       2016   
25                0.00  2016-01-03           1             3       2016   
26                0.00  2016-01-03           1             3       2016   
27                0.00  2016-01-03           1             3       2016   
28                0.37  2016-01-03           1             3       2016   
29                0.55  2016-01-03           1             3       2016   
30                0.15  2016-01-03           1             3       2016   

      Station.City Station.Code    Station.Location Station.State  \
20        Kotzebue          OTZ        Kotzebue, AK        Alaska   
21        Mc Grath          MCG        Mc Grath, AK        Alaska   
22            Nome          OME            Nome, AK        Alaska   
23        Northway          ORT        Northway, AK        Alaska   
24          Palmer          PAQ          Palmer, AK        Alaska   
25      Petersburg          PSG      Petersburg, AK        Alaska   
26   Puntilla Lake          PTI   Puntilla Lake, AK        Alaska   
27          Shemya          SYA          Shemya, AK        Alaska   
28           Sitka          SIT           Sitka, AK        Alaska   
29         Skagway          SGY         Skagway, AK        Alaska   
30  St Paul Island          SNP  St Paul Island, AK        Alaska   

    Data.Temperature.Avg Temp  Data.Temperature.Max Temp  \
20                         27                         33   
21                         30                         39   
22                         29                         32   
23                          0                          8   
24                         37                         42   
25                         60                         60   
26                         60                         60   
27                         60                         60   
28                         43                         46   
29                         38                         42   
30                         32                         35   

    Data.Temperature.Min Temp  Data.Wind.Direction  Data.Wind.Speed  
20                         20                   11            11.76  
21                         20                   15             3.70  
22                         25                    6            12.86  
23                         -9                   20             0.36  
24                         32                    8            10.50  
25                         60                   18             1.83  
26                         60                    0             0.00  
27                         60                    0             0.00  
28                         39                   19            11.26  
29                         33                   14             5.20  
30                         29                   22             9.03

In [38]:
df.iloc[20:30,0:5].values

array([[0.1, '2016-01-03', 1, 3, 2016],
       [0.01, '2016-01-03', 1, 3, 2016],
       [0.08, '2016-01-03', 1, 3, 2016],
       [0.0, '2016-01-03', 1, 3, 2016],
       [0.4, '2016-01-03', 1, 3, 2016],
       [0.0, '2016-01-03', 1, 3, 2016],
       [0.0, '2016-01-03', 1, 3, 2016],
       [0.0, '2016-01-03', 1, 3, 2016],
       [0.37, '2016-01-03', 1, 3, 2016],
       [0.55, '2016-01-03', 1, 3, 2016]], dtype=object)

In [39]:
df.iloc[20:30,0:5].index

RangeIndex(start=20, stop=30, step=1)

In [42]:
list(df.iloc[20:30,0:5].values)[1:]

[array([0.01, '2016-01-03', 1, 3, 2016], dtype=object),
 array([0.08, '2016-01-03', 1, 3, 2016], dtype=object),
 array([0.0, '2016-01-03', 1, 3, 2016], dtype=object),
 array([0.4, '2016-01-03', 1, 3, 2016], dtype=object),
 array([0.0, '2016-01-03', 1, 3, 2016], dtype=object),
 array([0.0, '2016-01-03', 1, 3, 2016], dtype=object),
 array([0.0, '2016-01-03', 1, 3, 2016], dtype=object),
 array([0.37, '2016-01-03', 1, 3, 2016], dtype=object),
 array([0.55, '2016-01-03', 1, 3, 2016], dtype=object)]

In [ ]:
integer + loc